version: 2

sources:
    - name: sales
      description: This is the raw sales data
      database: practice
      schema: sales
      tables:
          - name: raw_sales
            description: This is the raw sales data
            loaded_at_field: loaded_at
            freshness: 
              error_after:
                count: 24
                period: hour
              warn_after:
                count: 12
                period: hour    
            columns:
              - name: date
                tests:
                  - not_null
              - name: salesperson
                tests:
                  - not_null
              - name: '"Lead Name"'
                tests:
                  - not_null
              - name: segment
                tests:
                  - not_null
                  - accepted_values:
                      values: ["Enterprise", "SMB", "Startup"]
              - name: region
                tests:
                  - not_null
                  - accepted_values:
                      values: ["APAC", "EMEA", "US"]